### PR TITLE
nfts added(fixed json type) & changed html according to json

### LINKED ISSUE #62: Add NFTs menu to the web-wallet
The same NFT menu item from the metaverse wallet should be added to this project, so the wallet at https://wallet.walt.id/ should also be able to see NFTs if the people use "connect wallet" as input option.

### PR DESCRIPTION
**Pull request by farahaidid**

### CODE REVIEW

File: pages/nfts/_chain/_id.vue [hunk 1]
```diff
@@ -10,10 +10,10 @@
     <div class="_window d-flex justify-content-center align-items-center">
         <div class="_window-content">
           <div class="pt-2">
-            <h1>{{nft.title}}</h1>
+            <h1>{{nft.token.title}}</h1>
             <div class="d-flex justify-content-center mb-3">
               <div style="height: 300px" class="d-flex align-items-center">
-                <img :src="nft.metadata.image" class="image-fluid mx-auto img-thumbnail nft-img" v-show="!showQR" @click="toggleShowQR()" />
+                <img :src="nft.token.transactionExternalUrl" class="image-fluid mx-auto img-thumbnail nft-img" v-show="!showQR" @click="toggleShowQR()" />
```
Comment (mikeplotean) [inline pages/nfts/_chain/_id.vue]: should be imageUrl
also please check it how an ipfs url is converted into using https

File: pages/nfts/_chain/_id.vue [hunk 2]
```diff
@@ -25,27 +25,27 @@
...
               <span class="col-12 px-3">
                   <h5>{{ $t('NFT.BLOCKCHAIN') }}</h5>
                   <p>{{ chain }}</p>
               </span>
               <span class="col-12 px-3">
                   <h5>{{ $t('NFT.DESCRIPTION') }}</h5>
-                  <p>{{ nft.metadata.description }}</p>
+                  <p>{{ nft.token.description }}</p>
               </span>
             </div>
```
Comment (mikeplotean) [inline pages/nfts/_chain/_id.vue:61]: missing 'View on blockchain explorer' and 'View on OpenSea' buttons

File: pages/nfts/_chain/old_id.vue [hunk 3]
```diff
@@ -0,0 +1,118 @@
+<template>
```
Comment (mikeplotean) [inline pages/nfts/_chain/old_id.vue]: please remove unnecessary code

File: pages/nfts/_chain/index.vue [hunk 4]
```diff
@@ -47,7 +57,8 @@ export default {
   },
   methods:{
     navToNFT(nft) {
-      this.$router.push({name: "nfts-chain-id", params: { chain: this.chain, id: nft.contract.address + ":" + nft.id.tokenId}})
+      // this.$router.push({name: "nfts-chain-id", params: { chain: this.chain, id: nft.contract.address + ":" + nft.id.tokenId}})
```
Comment (mikeplotean) [inline pages/nfts/_chain/index.vue:51]: please remove commented code

File: pages/nfts/_chain/index.vue [hunk 5]
```diff
@@ -7,11 +7,17 @@
             </form>
         </div>
         <div class="_scrollable d-flex flex-column align-items-center">
-          <div class="mx-auto w-50 mb-3" v-for="nft in filteredList" v-bind:key="nft.id.tokenId">
+          <!-- <div class="mx-auto w-50 mb-3" v-for="nft in filteredList" v-bind:key="nft.id.tokenId">
```
Comment (mikeplotean) [inline pages/nfts/_chain/index.vue]: please remove commented code

File: pages/nfts/_chain/index.vue [hunk 6]
```diff
@@ -35,10 +41,14 @@ export default {
       })
     }
   },
+  // eslint-disable-next-line
   async asyncData ({ $axios, $auth, route }) {
     if($auth.user.ethAccount != null) {
-        const nfts = await $axios.$get("/nftkit/nft/chain/" + route.params.chain + "/owner/" + $auth.user.ethAccount)
-        return { nfts }
+        // const nfts = await $axios.$get("/nftkit/nft/chain/" + route.params.chain + "/owner/" + $auth.user.ethAccount)
+        return {
```
Comment (mikeplotean) [inline pages/nfts/_chain/index.vue]: please remove the sample data, it was suggested to be used for testing purpose only

File: pages/nfts/_chain/_id.vue [hunk 7]
```diff
@@ -72,16 +72,37 @@ export default {
...
     showRedeem() {
       return this.$route.query.redeem == "true"
     }
   },
-  async asyncData ({ $axios, $auth, route }) {
+  async asyncData () {
     // TODO: get info for single token
-    const nfts = await $axios.$get("/nftkit/nft/chain/" + route.params.chain + "/owner/" + $auth.user.ethAccount)
-    return {nfts}
+    // const nfts = await $axios.$get("/nftkit/nft/chain/" + route.params.chain + "/owner/" + $auth.user.ethAccount)
```
Comment (mikeplotean) [inline pages/nfts/_chain/_id.vue]: please remove the sample data, it was suggested to be used for testing purpose only

File: pages/nfts/_chain/_id.vue [hunk 8]
```diff
@@ -25,27 +25,27 @@
...
+              <!-- <span class="col-12 px-3">
                   <h5>{{ $t('NFT.TOKEN_STANDARD') }}</h5>
                   <p>{{ nft.id.tokenMetadata.tokenType }}</p>
-              </span>
+              </span> -->
               <span class="col-12 px-3">
                   <h5>{{ $t('NFT.BLOCKCHAIN') }}</h5>
                   <p>{{ chain }}</p>
               </span>
               <span class="col-12 px-3">
```
Comment (mikeplotean) [inline pages/nfts/_chain/_id.vue]: please move description above contract address

File: pages/nfts/_chain/_id.vue [hunk 9]
```diff
@@ -25,27 +25,27 @@
...
-                  <p>{{ nft.contract.address }}</p>
+                  <p>{{ nft.address }}</p>
               </span>
               <span class="col-12 px-3">
                   <h5>{{ $t('NFT.TOKEN_ID') }}</h5>
-                  <p>{{ nft.id.tokenId }}</p>
+                  <p>{{ nft.token.tokenId }}</p>
               </span>
-              <span class="col-12 px-3">
+              <!-- <span class="col-12 px-3">
```
Comment (mikeplotean) [inline pages/nfts/_chain/_id.vue]: please display the token standard as well

**Review by mikeplotean — CHANGES_REQUESTED** [review]
please take a look at the comments
and also at the paddings, see image below
padding

File: pages/nfts/_chain/_id.vue [hunk 10]
```diff
@@ -8,45 +8,60 @@
...
+                </div>
               </button>
+              <button v-if="isRedeemable" type="button" class="btn btn-primary mt-2" @click="toggleShowQR" :disabled="isRedeemed"><i class="bi bi-upc-scan me-2"></i><span v-if="showQR">Close QR code</span><span v-if="!showQR">Show QR code</span></button>
             </div>
             <div class="text-left pt-2">
+              <div v-if="isRedeemable && isRedeemed" class="alert alert-info mt-3 mx-3">
+                <em>This token has already been redeemed.</em>
+              </div>
               <span class="col-12 pb-3">
                   <h5>{{ $t('NFT.NAME') }}</h5>
```
Comment (mikeplotean) [inline pages/nfts/_chain/_id.vue]: maybe remove the 'Name', since it's already displayed as title

**Review by mikeplotean — CHANGES_REQUESTED** [review]
- [ ] could you please add the "NoImageAvailable.jpg" asset as well?
- [ ] also, vertical padding still looks the same
Untitled

**Review by mikeplotean — APPROVED** [review]
